### ISSUE TITLE
Wording for new home page

### ISSUE THREAD

**Issue by NathanW2** [qgisau/qgis-au.github.io#1]
@Drewfore if you get a sec are you able to put together some wording you think we can show on the home page

**Comment by EmHain8** [comment]
Intro blurb something like this: 
The QGIS AU group was established in 2017 with the main objective to support QGIS Users throughout Australia and its neighboring regions. We have an active online discussion group and our mission is to engage and grow our community. We are made up of end-users, hobbyists, scientists, professionals, students and developers. All are welcome and we recognize the importance of everyone's input.

I like how [Brasil ](https://qgisbrasil.org/#como-participar) has links to QGIS facets: reporting bugs, documentation, tutorials & etc 

Overall, the design of the QGIS User Groups pages are a bit naff - with Brasil being the best of the lot.

We don't want to crowd the front page, but I think in the first instance, we could just put some of the relevant links that are Switzerland's page after the blurb, so that at least it is a bit meaningful - unless you want to include a Resources tab at the getgo, including:

Links about QGIS

    [QGIS Website (international project)](http://www.qgis.org/)
    [QGIS bugtracker](http://hub.qgis.org/)
    [QGIS Plugins](http://plugins.qgis.org/plugins/)
    [QGIS Blog](http://blog.qgis.org/)
    [QGIS Planet (News/Blog aggregation)](http://planet.qgis.org/)
    [QGIS Podcasts](http://qgispodcast.libsyn.com/)
    [QGIS projekt at Github](https://github.com/qgis/)
    [QGIS Tutoirals](https://www.qgistutorials.com/en/)

Other QGIS-related projects

    [OSGeo Website](http://www.osgeo.org/)
    [GRASS GIS](http://grass.osgeo.org/) (Desktop/Analysis-GIS)
    [Postgis Project](http://www.postgis.org/) (spatial database)
    [SpatiaLite Project](http://www.gaia-gis.it/gaia-sins/index.html) (light-weight spatial database)
    [GEOS Project](http://trac.osgeo.org/geos/) (geometry library)
    [Proj4 Project](http://trac.osgeo.org/proj/) (projections library)
    [GDAL/OGR](http://www.gdal.org/) (GIS-format library, raster and vector)

**Comment by Drewfore** [comment]
@EmHain8 that blurbs on the money I reckon, something simple like that will be fine. I reckon we lose the reference to neighbouring regions, we discussed a while back that we should just reference Australia as that is the area where we can have influence and we have good coverage on either side. This also encourages neighbouring regions to run their own user groups to suit their local users. I also noticed the description on the Google Group still references NZ, I thought we ditched that way back or it may have slipped in again? I think we should update that as well just to be AU

**Comment by EmHain8** [comment]
Thanks @Drewfore I was iffy about putting it in but was still unsure. And yup remove the NZ reference too - I just did that.

**Comment by NathanW2** [comment]
Thanks @EmHain8 @Drewfore  I'm working on this now.  The layout of the site won't be very fancy first part but I'm going to keep working on little tweaks after we have it deployed out.  As long as we have a landing page and some links that will be a good start.

**Comment by Drewfore** [comment]
Yeah keep it super simple

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by johnwbryant** [comment]
All done! Looks great :)
